# dev configuration (use docker-compose up will use docker-compose.yml and docker-comspoe.override.yml both)
# os: mac
version: "3.8"

services:
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
        ports:
            - '8000:8000'
        volumes:
            - local_dynamodb-v:/home/dynamodblocal/data
        working_dir: /home/dynamodblocal
        user: root
volumes:
    local_dynamodb-v:


